/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MaquinaExpendedora;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ale
 */
public class MaquinaExpendedora extends javax.swing.JFrame {

    /**
     * Creates new form MaquinaExpendedora
     */
    public MaquinaExpendedora() {
        initComponents();
    }
    
    private static int precio = 17;
    private static int cocas = 27;
    private static int monedauno = 80;
    private static int monedados = 50;
    private static int monedacinco = 100;
    private static int monedadiez = 35;
    private static int billeteveinte = 60;
    private static int billetecincuenta = 35;
    private static int billetecien = 123;
    private static int billetedoscientos = 180;
    private static int billetequinientos = 150;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtIngresar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblMon = new javax.swing.JLabel();
        lblMon2 = new javax.swing.JLabel();
        lblMon3 = new javax.swing.JLabel();
        lblMon4 = new javax.swing.JLabel();
        lblMon5 = new javax.swing.JLabel();
        lblMon6 = new javax.swing.JLabel();
        lblMon7 = new javax.swing.JLabel();
        lblMon8 = new javax.swing.JLabel();
        btnDespachar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCocas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLatas = new javax.swing.JLabel();
        bnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese cantidad monetaria");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Costo del producto");

        lblprecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblprecio.setText("$ 17.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cambio");

        lblCambio.setText("$ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblprecio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(58, 58, 58)
                                .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMon2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(lblMon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMon6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMon5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(lblMon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMon7)
                            .addComponent(lblMon8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblprecio))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCambio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMon5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMon6)
                .addGap(23, 23, 23))
        );

        btnDespachar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDespachar.setText("Servir");
        btnDespachar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespacharActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel4.setText("Coca Cola");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblCocas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCocas.setText(".....");
        lblCocas.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCocas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCocas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sin título.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Latas disponibles:");

        lblLatas.setText("27");

        bnBorrar.setText("Borrar");
        bnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblLatas)
                                .addGap(30, 30, 30)
                                .addComponent(btnDespachar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDespachar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(bnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblLatas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDespacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespacharActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.valueOf(txtIngresar.getText());
        //lblprecio.setText(String.format("$ %s . 00", precio));
        
        
        if(cantidad < precio ){
            JOptionPane.showMessageDialog(this, String.format("Cantidad Insuficiente", JOptionPane.WARNING_MESSAGE));
        }
        if(cantidad == precio){
            if(cantidad > 500){
                billetequinientos = billetequinientos + 1;
            }if(cantidad > 200){
                billetedoscientos = billetedoscientos + 1;
            }if(cantidad > 100){
                billetecien = billetecien + 1;
            }if(cantidad > 50){
                billetecincuenta = billetecincuenta + 1;
            }if(cantidad > 20){
                billeteveinte = billeteveinte + 1;
            }if (cantidad > 10){
                monedadiez = monedadiez + 1;
            }if (cantidad >5){
                monedacinco = monedacinco + 1;
            }if(cantidad > 2){
                monedados = monedados + 1;
            }if (cantidad >= 1){
                monedauno = monedauno + 1;
            }
            System.out.println("Monedas de un peso");
            System.out.println(monedauno);
            System.out.println("Monedas de dos pesos");
            System.out.println(monedados);
            System.out.println("Monedas de cinco pesos");
            System.out.println(monedacinco);
            System.out.println("Monedas de diez pesos");
            System.out.println(monedadiez);
            System.out.println("Billetes de veinte pesos");
            System.out.println(billeteveinte);
            System.out.println("Billetes de cincuenta pesos");
            System.out.println(billetecincuenta);
            System.out.println("Billetes de cien pesos");
            System.out.println(billetecien);
            System.out.println("Billetes de doscientos pesos");
            System.out.println(billetedoscientos);
            System.out.println("Billetes de quinientos pesos");
            System.out.println(billetequinientos);
            System.out.println("Numero de cocas");
            System.out.println(cocas);
            lblCocas.setText(String.valueOf("Puede recoger su producto"));
        }
        if(cantidad > precio){
            Integer res = cantidad - precio;
            lblCambio.setText(String.format("$ %s . 00", res));
            switch(cantidad){
                case 500:
                    billetequinientos = billetequinientos + 1;
                      if(res >= 400){
                         billetedoscientos = billetedoscientos - 2;
                         lblMon6.setText(String.valueOf("Billete de $ 200 . 00 = 2"));
                         res = res - 400;
                      }if(res >= 200){
                         billetedoscientos = billetedoscientos - 1;
                         lblMon6.setText(String.valueOf("Billete de $ 200 . 00 = %1"));
                         res = res - 200;
                      }if(res >= 100){
                         billetecien = billetecien - 1;
                         lblMon8.setText(String.valueOf("Billete de $ 100 . 00 = 1"));
                         res = res - 100;
                      }if(res >= 50){
                         billetecincuenta = billetecincuenta - 1;
                         lblMon5.setText(String.valueOf("Billete de $ 50 . 00 = 1"));
                         res = res - 50;
                      }if(res >= 40){
                         billeteveinte = billeteveinte - 2;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 40;
                      }if(res >= 20){
                         billeteveinte = billeteveinte - 1;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 20;
                      }if (res >= 10){
                         monedadiez = monedadiez - 1;
                         lblMon3.setText(String.valueOf("Moneda de $ 10 . 00 = 1"));
                         res = res - 10;
                      }if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                      
                      break;
                case 200:
                    billetedoscientos = billetedoscientos + 1;
                      if(res >= 100){
                         billetecien = billetecien - 1;
                         lblMon8.setText(String.valueOf("Billete de $ 100 . 00 = 1"));
                         res = res - 100;
                      }if(res >= 50){
                         billetecincuenta = billetecincuenta - 1;
                         lblMon5.setText(String.valueOf("Billete de $ 50 . 00 = 1"));
                         res = res - 50;
                      }if(res >= 40){
                         billeteveinte = billeteveinte - 2;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 40;
                      }if(res >= 20){
                         billeteveinte = billeteveinte - 1;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 20;
                      }if (res >= 10){
                         monedadiez = monedadiez - 1;
                         lblMon3.setText(String.valueOf("Moneda de $ 10 . 00 = 1"));
                         res = res - 10;
                      }if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break;
                case 100:
                    billetecien = billetecien + 1;
                      if(res >= 50){
                         billetecincuenta = billetecincuenta - 1;
                         lblMon5.setText(String.valueOf("Billete de $ 50 . 00 = 1"));
                         res = res - 50;
                      }if(res >= 40){
                         billeteveinte = billeteveinte - 2;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 40;
                      }if(res >= 20){
                         billeteveinte = billeteveinte - 1;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 20;
                      }if (res >= 10){
                         monedadiez = monedadiez - 1;
                         lblMon3.setText(String.valueOf("Moneda de $ 10 . 00 = 1"));
                         res = res - 10;
                      }if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break;  
                case 50:
                    billetecincuenta = billetecincuenta + 1;
                      if(res >= 40){
                         billeteveinte = billeteveinte - 2;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 40;
                      }if(res >= 20){
                         billeteveinte = billeteveinte - 1;
                         lblMon4.setText(String.valueOf("Billete de $ 20 . 00 = 1"));
                         res = res - 20;
                      }if (res >= 10){
                         monedadiez = monedadiez - 1;
                         lblMon3.setText(String.valueOf("Moneda de $ 10 . 00 = 1"));
                         res = res - 10;
                      }if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break; 
                case 20:
                    billeteveinte = billeteveinte + 1;
                      if (res >= 10){
                         monedadiez = monedadiez - 1;
                         lblMon3.setText(String.valueOf("Moneda de $ 10 . 00 = 1"));
                         res = res - 10;
                      }if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break; 
                case 10:
                    monedadiez = monedadiez + 1;
                      if (res >= 5){
                         monedacinco = monedacinco - 1;
                         lblMon7.setText(String.valueOf("Moneda de $ 5 . 00 = 1"));
                         res = res - 5;
                      }if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break; 
                case 5:
                    monedacinco = monedacinco + 1;
                      if(res >= 2){
                         monedados = monedados - 1;
                         lblMon2.setText(String.valueOf("Moneda de $ 2 . 00 = 1"));
                         res = res - 2;
                      }if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break; 
                case 2:
                    monedados = monedados + 1;
                      if (res >= 1){
                         monedauno = monedauno - 1;
                         lblMon.setText(String.valueOf("Moneda de $ 1 . 00 = 1"));
                         res = res - 1;
                      }
                      cocas = cocas - 1;
                     
                      break; 
                case 1:
                    monedauno = monedauno + 1;
                    cocas = cocas - 1;
                    break;
                default:
            }
            System.out.println("Monedas de un peso");
            System.out.println(monedauno);
            System.out.println("Monedas de dos pesos");
            System.out.println(monedados);
            System.out.println("Monedas de cinco pesos");
            System.out.println(monedacinco);
            System.out.println("Monedas de diez pesos");
            System.out.println(monedadiez);
            System.out.println("Billetes de veinte pesos");
            System.out.println(billeteveinte);
            System.out.println("Billetes de cincuenta pesos");
            System.out.println(billetecincuenta);
            System.out.println("Billetes de cien pesos");
            System.out.println(billetecien);
            System.out.println("Billetes de doscientos pesos");
            System.out.println(billetedoscientos);
            System.out.println("Billetes de quinientos pesos");
            System.out.println(billetequinientos);
            System.out.println("Numero de cocas");
            System.out.println(cocas);
            lblLatas.setText(String.format("%s", cocas));
            lblCocas.setText(String.valueOf("Puede recoger su producto"));
            JOptionPane.showMessageDialog(this,String.format("Puede recoger su cambio"), "Despachando", JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_btnDespacharActionPerformed

    private void txtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIngresarActionPerformed

    private void bnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBorrarActionPerformed
        // TODO add your handling code here:
        txtIngresar.setText(String.valueOf(""));
        lblMon6.setText(String.valueOf(""));
        lblMon8.setText(String.valueOf(""));
        lblMon5.setText(String.valueOf(""));
        lblMon4.setText(String.valueOf(""));
        lblMon3.setText(String.valueOf(""));
        lblMon7.setText(String.valueOf(""));
        lblMon2.setText(String.valueOf(""));
        lblMon.setText(String.valueOf(""));
        lblCocas.setText(String.valueOf("....."));
        lblCambio.setText(String.valueOf("$ 0.00"));
 
    }//GEN-LAST:event_bnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaquinaExpendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaquinaExpendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaquinaExpendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaquinaExpendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaquinaExpendedora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBorrar;
    private javax.swing.JButton btnDespachar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCocas;
    private javax.swing.JLabel lblLatas;
    private javax.swing.JLabel lblMon;
    private javax.swing.JLabel lblMon2;
    private javax.swing.JLabel lblMon3;
    private javax.swing.JLabel lblMon4;
    private javax.swing.JLabel lblMon5;
    private javax.swing.JLabel lblMon6;
    private javax.swing.JLabel lblMon7;
    private javax.swing.JLabel lblMon8;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JTextField txtIngresar;
    // End of variables declaration//GEN-END:variables
}
